### ISSUE TITLE
Logo issue: logo.png doesn't load

### ISSUE THREAD

**Issue by karlzre** [laurentalacoque/TouchSelfie-extended#48]
Hey Laurent,

I just installed and tested your photobooth and it's great !!!

I don't find a way to put logo.png on the photos, according to the readme this should be during setup.sh but I couldn't find the option.

I also manually changed the configuration.json where logo is set to "null", I changed it to logo.png but the script now crashes.
Could you indicate where to define it?

---- Original message ----

Bonjour Laurent, 

Je viens d'installer et tester ton photobooth, c'est génial !!!

Je ne trouve juste pas comment mettre le logo.png sur les photos, d'apres le readme cela devrait être pendant le setup.sh, mais je n'ai pas l'option.

J'ai aussi changé dans configuration.json le logo est "null", j'ai essaye de le changer en mettant logo.png mais le script ne démarre plus.

Peux tu m'indiquer ou le définir ?

Merci d'avance.

**Comment by laurentalacoque** [comment]
Will take a look into this ;)

**Comment by laurentalacoque** [comment]
I should (really) add this in setup, but you could try to 
- put your logo file in the `scripts` directory (e.g. `scripts/mylogo.png`)
- change the `configuration.json` `logo_file` key to something like this: `"logo_file":"mylogo.png",`
- relaunch the photobooth in the `scripts` directory using `python user_interface.py -df` (this will disable fullscreen mode
- copy/paste any error that cause the crash in this issue report

**Comment by karlzre** [comment]
Hi laurent, 

This looks to works

**Comment by laurentalacoque** [comment]
Nice!
Closing the bug then.
