### ISSUE TITLE
Exit touchSelfie: long-press doesn't work

### ISSUE THREAD

**Issue by karlzre** [laurentalacoque/TouchSelfie-extended#49]
Hello Laurent,

Can you please tell me how to exit TouchSelfie using long press?
Physical keyboard <ESC> key works, but long pressing the screen doesn't.

---- original message ----

Bonjour Laurent, 

Peux tu m'indiquer comment quitter TouchSelfie ?

Avec un clavier la touche Esc fait l'affaire mais sans clavier, tu indique un long press, mais cela ne semble pas fonctionner.

Merci

**Comment by laurentalacoque** [comment]
Hey @karlzre!
Thanks for your input.

Could you please try harder and really press Touchselfie's background during at lease 3 seconds?
When you lift your finger after a (very) long press, a dialog should appear from which you can choose to exit the application

**Comment by karlzre** [comment]
Iv' try a long press more tahn 3 sec, on different places in touch selfie but didn't work.

Maybe a misconfiguration or issue on my touchscreen

**Comment by laurentalacoque** [comment]
Unable to reproduce the bug, I'm closing it.
Feel free to reopen
