### ISSUE TITLE
Mode 4 photo - Proposition d'amelioration

### ISSUE THREAD

**Issue by karlzre** [laurentalacoque/TouchSelfie-extended#50]
Hello,
In the 4 pictures mode, would it be possible to take 3 photos only and add a logo in one of the pictures?

---- original message ----
Bonjour, 

Dans le mode 4 photos, serait il possible de ne faire que 3 photos et d'ajouter un logo dans une des cases ?

Merci

**Comment by laurentalacoque** [comment]
Hey ;)
I'm not sure this reflects the mainstream need, but here's a quick and dirty trick:
Change the /scripts/collage_four_square.png picture to add your logo in one of the rectangles

This image is loaded on top of the 4 snaps of this mode.

You'll still have 4 snaps taken though...
If you want to  modify this behaviour, take a look at `scripts/user_interface.py` line 454 (`elif mode == "Four"`)
