### ISSUE TITLE
Error : invalid scope when authenticating the application on google servers

### ISSUE THREAD

**Issue by staff21** [laurentalacoque/TouchSelfie-extended#66]
Hello, no way to finish the ./setup.sh 
When i use the ./setup.sh a very helpfull help help me to create the google_client_id.json that i copy to the script area. 
just after : 
At the end, the raspi open a chronium with this link : 
 https://accounts.google.com/o/oauth2/auth?scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fphotoslibrary.appendonly+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fphotoslibrary.readonly.appcreateddatahttps%3A%2F%2Fwww.googleapis.com%2Fauth%2Fgmail.send&redirect_uri=http%3A%2F%2Flocalhost%3A8090%2F&response_type=code&client_id=1042781456115-4ctitr3vhvt3q5fbflo4lhi9ub4ov3se.apps.googleusercontent.com&access_type=offline

=> 400 that's an error.

**Comment by staff21** [comment]
solved, i was not using the master source.

**Comment by laurentalacoque** [comment]
Glad you found out ;)
